#!/bin/bash
set -ex

# Get Odoo version
version="$DOCKER_TAG"
if [ "$version" == latest ]; then
    version=11.0
fi

if [ -z "$IMAGE_NAME" ]; then
    IMAGE_NAME="$DOCKER_REPO:$DOCKER_TAG"
fi

BUILD_ARGS=""
if [ "$version" == "8.0" ]; then
    BUILD_ARGS="${BUILD_ARGS} --build-arg WKHTMLTOPDF_VERSION=0.12.1.2"
    BUILD_ARGS="${BUILD_ARGS} --build-arg WKHTMLTOPDF_CHECKSUM=3ae78d7f7323f6bbc76238eb548729f17ab0db5bed59455a023b9c93fb0c35c4"
fi

# See http://label-schema.org/rc1/#build-time-labels
for target in base onbuild; do
    suffix=''
    if [ "$target" == onbuild ]; then
        suffix="-$target"
    fi
    time docker image build \
        --build-arg VCS_REF="$GIT_SHA1" \
        --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
        --build-arg ODOO_SOURCE="${ODOO_SOURCE:-OCA/OCB}" \
        --build-arg ODOO_VERSION="$version" \
        ${BUILD_ARGS} \
        --file "$version.Dockerfile" \
        --tag "$IMAGE_NAME$suffix" \
        --target $target \
        .
done
